import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeProvider";
import { Poppins } from 'next/font/google'
import CustomCursor from "@/components/CustomCursor";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // normal, semi-bold, bold
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="pt-[80px]">
        <ThemeProvider>
<CustomCursor/>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
